language: node_js
node_js:
  - 14.4.0
branches:
  only:
    - master
    - dev
after_script:
  - COVERALLS_REPO_TOKEN=$coveralls_repo_token npm run coveralls
deploy:
  provider: netlify
  site: phil-vigus.netlify.app
  auth: $netlify_repo_token
  edge: true # opt in to dpl v2
