language: node_js
node_js:
- 14.4.0
cache: yarn
deploy:
  provider: heroku
  api_key:
    secure: qtXVfpMYcPsysKUqC/y52Yg+QC3cAyj/6//uq+P5wvhAUn8PCdpmygGsCmcKr/W3+NdL2bWdLwIvAvGiq0TA/7oJfRlSIwiytLE7BO+hT7Drnl3qbtv5JMKPLvwgIPxSnwRmuUd0/MTFpJv9HzOtKaJEERG4vTLW+XYiAtWxhe8i6TUqyvo37XZHxoXABjEVcszF0fku5bvaeK7erJmjovlTGrP4AlVAujYvAyNJArUpUkGWEAhauhdyFYNwc8n3dvVigxlaR/Sh9pVjUr8J6GnL5v6P/ll/DeRVF7yFlCf9rvTUrRZLd2OwQdSz2/FVLrYoRPbIqQOIMjyoXQfQYwkZ3ahNnfI/Xg52jvyMnNhN/JslBjbX7pPVeZCgHvXBIHg5z4C6bx32h442zvEwdumFpOp7+PeMAcBJ9ksg6oLf3QznfVptcusQUhbTZ+Lvx5sgkq7Mf48MlvZXmIwID5JFA4lSwh2BFIHfCoN193bs0w7E/jJf/WmkjAU9TWUC0UmO/JXbi9OHOdv7sBglMrZzE8/TisB6O5ElVJl+QHztOY16J4lVhJAr5HvayfFNMdy+p7YquQFZw/db/sWeHXpJwhqtWsOLE98TsW8NQZcsuPccojF/IsQfAUcjpfd+1FWKnke6O9b6MVm8rx5RQi3sG6syJ1w7zC3aaVbA3EQ=
  app: phil-dev-portfolio
  on:
    repo: PhilipVigus/dev-portfolio
  skip_cleanup: 'true'
